/* ============================================================
   TUTORIAL — Step-by-step Bayesian inference walkthrough
   ============================================================

   Teaches the player CS109 concepts through guided gameplay:
   1. Prior — uniform belief
   2. Observation — sonar ping with Gaussian noise
   3. Likelihood — ring of probable locations
   4. Posterior — Bayes' theorem update
   5. Prediction — diffusion for monster movement
   6. Hands-on — player takes control
   ============================================================ */

const STEPS = [
  {
    title: 'Welcome, Agent',
    text: `You're trapped in a dungeon. <strong>Monsters</strong> hide in the fog.
           Your only tool: a <strong>sonar sensor</strong> that estimates distance to the nearest monster — but it's noisy.`,
    math: null,
    highlight: null,
    action: 'next',  // just click next
  },
  {
    title: 'Step 1: The Prior',
    text: `Before any observations, you have <strong>no idea</strong> where the monsters are.
           Your belief is <strong>uniform</strong> — every cell is equally likely.
           Look at the Belief Map panel →`,
    math: 'P(monster at cell) = 1/N for all cells',
    highlight: 'belief-panel',
    action: 'next',
  },
  {
    title: 'Step 2: Observation',
    text: `Let's ping the sonar! You'll get a noisy distance reading.
           The reading is the <strong>true distance + Gaussian noise</strong>.
           <br><br>Press <kbd>Space</kbd> to scan.`,
    math: 'z = d_true + \u03b5,  \u03b5 ~ N(0, \u03c3\u00b2)',
    highlight: null,
    action: 'scan',  // wait for player to press space
  },
  {
    title: 'Step 3: The Likelihood',
    text: `See the ring on the heatmap? That's the <strong>likelihood function</strong> —
           it shows which cells are consistent with the sensor reading.
           Cells at distance ≈ ${'{reading}'} from you are most likely.`,
    math: 'L(cell) = exp(-|d(cell) - z|\u00b2 / 2\u03c3\u00b2)',
    highlight: null,
    action: 'next',
  },
  {
    title: 'Step 4: Bayes\' Theorem!',
    text: `The <strong>posterior</strong> = prior \u00d7 likelihood, normalized.
           This is the heart of Bayesian inference — combining what you
           believed before with new evidence.`,
    math: 'P(cell | z) \u221d P(cell) \u00d7 L(z | cell)',
    highlight: 'belief-panel',
    action: 'next',
  },
  {
    title: 'Step 5: Prediction',
    text: `Monsters move! So each turn we <strong>diffuse</strong> the belief
           by convolving with a Gaussian kernel. This is the <strong>prediction step</strong> —
           it accounts for our uncertainty about monster movement.`,
    math: 'P\u2032(cell) = \u2211 P(cell\u2032) \u00d7 K(cell - cell\u2032)',
    highlight: null,
    action: 'next',
  },
  {
    title: 'Step 6: The Panels',
    text: `Watch the side panels as you play:
           <br>\u2022 <strong>Entropy</strong> — your total uncertainty (drops as you learn)
           <br>\u2022 <strong>Beta Distribution</strong> — how reliable your sensor is
           <br>\u2022 <strong>Expected Value</strong> — safest move direction
           <br>\u2022 <strong>Music</strong> — generated by a Markov chain, tenser when uncertain!`,
    math: null,
    highlight: null,
    action: 'next',
  },
  {
    title: 'Your Turn!',
    text: `Navigate to the <strong style="color:#ffcc00">EXIT</strong> without hitting monsters.
           Use the heatmap and EV arrows to guide your decisions.
           <br><br><kbd>\u2190\u2191\u2193\u2192</kbd> Move &nbsp; <kbd>Space</kbd> Scan &nbsp; <kbd>R</kbd> Restart
           <br><br>Good luck, Bayesian agent.`,
    math: null,
    highlight: null,
    action: 'start',
  },
];

export class Tutorial {
  constructor(game) {
    this.game = game;
    this.step = 0;
    this.active = false;
    this.box = document.getElementById('tutorial-box');
    this.waitingForAction = null;
  }

  start() {
    this.active = true;
    this.step = 0;
    this.game.phase = 'TUTORIAL';
    this.game.tutorialActive = true;
    this.show();
  }

  show() {
    if (this.step >= STEPS.length) {
      this.end();
      return;
    }

    const s = STEPS[this.step];
    let text = s.text;

    // Fill in dynamic values
    if (this.game.lastReading !== null) {
      text = text.replace('{reading}', this.game.lastReading.toFixed(1));
    }

    let html = `<h3>${s.title}</h3><p>${text}</p>`;
    if (s.math) {
      html += `<p class="math">${s.math}</p>`;
    }

    if (s.action === 'next' || s.action === 'start') {
      const label = s.action === 'start' ? 'Begin!' : 'Next \u2192';
      html += `<button class="tut-next" id="tut-next-btn">${label}</button>`;
      this.waitingForAction = null;
    } else if (s.action === 'scan') {
      this.waitingForAction = 'scan';
    }

    this.box.innerHTML = html;
    this.box.classList.remove('hidden');

    // Highlight panel
    this._clearHighlights();
    if (s.highlight) {
      const el = document.getElementById(s.highlight);
      if (el) el.classList.add('panel-highlight');
    }

    // Bind next button
    const btn = document.getElementById('tut-next-btn');
    if (btn) {
      btn.addEventListener('click', () => this.advance());
    }
  }

  advance() {
    this.step++;
    if (this.step >= STEPS.length) {
      this.end();
    } else {
      this.show();
    }
  }

  // Called when player performs an action during tutorial
  onAction(action) {
    if (!this.active) return false;
    if (this.waitingForAction === action) {
      this.waitingForAction = null;
      // Small delay so player sees the result
      setTimeout(() => this.advance(), 600);
      return true;
    }
    // Block non-expected actions during tutorial (except the waited one)
    if (this.waitingForAction) return false;
    return false;
  }

  end() {
    this.active = false;
    this.game.phase = 'PLAYING';
    this.game.tutorialActive = false;
    this.box.classList.add('hidden');
    this._clearHighlights();
  }

  _clearHighlights() {
    document.querySelectorAll('.panel-highlight').forEach(el =>
      el.classList.remove('panel-highlight'));
  }
}
